#Configuracion
#Sun May 10 22:30:41 MST 2026
registration.image.last.directory=C\:\\Users\\Admin\\OneDrive\\Desktop
registration.window.height=850
registration.window.width=1200
registration.window.x=518
registration.window.y=111
users.export.pdf=C\:\\Users\\Admin\\OneDrive\\Documents
