#Configuracion
#Wed May 06 10:36:11 MST 2026
registration.image.last.directory=C\:\\Users\\Admin\\OneDrive\\Desktop
registration.window.height=700
registration.window.width=985
registration.window.x=190
registration.window.y=30
users.export.pdf=C\:\\Users\\Admin\\OneDrive\\Documents
